In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/Advertising.csv", index_col = 0)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [5]:
data.shape

(200, 4)

In [6]:
data.corr()

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [7]:
X = data.iloc[:,:-1]
X.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [8]:
y = data.iloc[:,-1]
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: sales, Length: 200, dtype: float64

In [9]:
X.shape

(200, 3)

In [10]:
y.shape

(200,)

In [12]:
type(X)

pandas.core.frame.DataFrame

In [11]:
type(y)

pandas.core.series.Series

In [13]:
X.drop(['newspaper'], axis=1, inplace=True)

In [14]:
X.head()

TV  radio
1  230.1   37.8
2   44.5   39.3
3   17.2   45.9
4  151.5   41.3
5  180.8   10.8

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,random_state=110)

In [16]:
X_train.head()

TV  radio
166  234.5    3.4
26   262.9    3.5
44   206.9    8.4
64   102.7   29.6
182  218.5    5.4

In [17]:
X_train.shape

(160, 2)

In [18]:
X_test.shape

(40, 2)

In [ ]:
y_train.shape

(160,)

In [ ]:
y_test.shape

(40,)

In [ ]:
X_train.head()

TV  radio
166  234.5    3.4
26   262.9    3.5
44   206.9    8.4
64   102.7   29.6
182  218.5    5.4

In [ ]:
X_test.head()

TV  radio
169  215.4   23.6
198  177.0    9.3
148  243.2   49.0
125  229.5   32.3
141   73.4   17.0

In [ ]:
X_train.tail()

TV  radio
90   109.8   47.8
126   87.2   11.8
16   195.4   47.7
62   261.3   42.7
129  220.3   49.0

In [ ]:
y_train

166    11.9
26     12.0
44     12.9
64     14.0
182    12.2
       ... 
90     16.7
126    10.6
16     22.4
62     24.2
129    24.7
Name: sales, Length: 160, dtype: float64

In [ ]:
y_test

169    17.1
198    12.8
148    25.4
125    19.7
141    10.9
66      9.3
152    11.6
21     18.0
72     12.4
87     12.0
42     17.1
101    11.7
29     18.9
28     15.9
120     6.6
43     20.7
186    22.6
56     23.7
199    25.5
80     11.0
119    15.9
139     9.6
31     21.4
188    17.3
83     11.3
78     14.2
54     21.2
192     9.9
136    11.6
11      8.6
93     19.4
39     10.1
117    12.2
184    26.2
116    12.6
30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64

In [ ]:
X_train.describe()

TV       radio
count  160.000000  160.000000
mean   145.585000   22.281875
std     86.935101   15.097481
min      0.700000    0.000000
25%     69.000000    8.350000
50%    150.650000   20.950000
75%    218.825000   36.525000
max    296.400000   49.600000

In [ ]:
X_train.columns

Index(['TV', 'radio'], dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[['TV', 'radio']] = scaler.fit_transform(X_train[['TV', 'radio']])
X_train.head()

TV     radio
166  1.025986 -1.254591
26   1.353692 -1.247946
44   0.707511 -0.922370
64  -0.494848  0.486247
182  0.841362 -1.121702

In [ ]:
X_train.describe()

TV         radio
count  1.600000e+02  1.600000e+02
mean  -1.110223e-16  2.747802e-16
std    1.003140e+00  1.003140e+00
min   -1.671821e+00 -1.480501e+00
25%   -8.837104e-01 -9.256920e-01
50%    5.844478e-02 -8.849534e-02
75%    8.451127e-01  9.463727e-01
max    1.740247e+00  1.815130e+00

In [ ]:
X_test.columns

Index(['TV', 'radio'], dtype='object')

In [ ]:
X_test[['TV', 'radio']] = scaler.fit_transform(X_test[['TV', 'radio']])
X_test.head()

TV     radio
169  0.770473 -0.274485
198  0.297303 -1.367078
148  1.113029  1.666204
125  0.944215  0.390239
141 -0.979272 -0.778759

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.intercept_

13.646875

In [ ]:
model.coef_

array([3.95940425, 2.76381841])

In [ ]:
X_train.columns

Index(['TV', 'radio'], dtype='object')

In [ ]:
y_pred_test = model.predict(X_test)
y_pred_test

array([15.93886121, 11.04566003, 22.65889082, 18.46395442,  7.61719419,
        5.77651784,  8.12345939, 16.95102253,  8.82293176,  9.97596351,
       16.13485265, 12.2048022 , 18.30748659, 15.6868618 ,  4.77145328,
       20.61990672, 19.97161342, 20.58203468, 23.15175158,  7.73169875,
       14.37110447,  8.01343962, 20.71245677, 15.83027029,  8.40675246,
       12.34357856, 19.1110411 ,  6.41039686, 12.72770106,  4.89593725,
       18.14165562,  8.18725431, 10.25730935, 23.55807482, 11.50119112,
        7.26941698, 12.18728352, 16.97243566, 10.1779425 , 20.26284029])

In [ ]:
y_test.tail()

30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64

In [ ]:
print(y_test)

169    17.1
198    12.8
148    25.4
125    19.7
141    10.9
66      9.3
152    11.6
21     18.0
72     12.4
87     12.0
42     17.1
101    11.7
29     18.9
28     15.9
120     6.6
43     20.7
186    22.6
56     23.7
199    25.5
80     11.0
119    15.9
139     9.6
31     21.4
188    17.3
83     11.3
78     14.2
54     21.2
192     9.9
136    11.6
11      8.6
93     19.4
39     10.1
117    12.2
184    26.2
116    12.6
30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64


In [ ]:
y_test.tail()

30     10.5
162    13.3
106    19.2
7      11.8
112    21.8
Name: sales, dtype: float64

In [ ]:
y_pred_train = model.predict(X_train)
y_pred_train

array([14.24170638, 15.55759151, 13.89893329, 13.03147017, 13.87798781,
       14.64690217, 17.1200731 ,  3.5756048 ,  7.61991582, 14.68638712,
        6.42658793, 21.06945121,  5.71519777,  7.08887417, 18.25413031,
       14.81301036, 17.94734165, 12.7224586 ,  8.10871296, 11.99460268,
       15.2076707 , 15.96770959, 12.57420656, 17.56000455, 15.18201234,
        8.39743607, 14.25728449, 13.30671771, 14.02238072, 18.27017982,
       15.07073151, 16.28061417, 13.5783494 , 10.62629871,  7.49027355,
       20.1945369 , 16.68304536, 18.02038378, 23.03219873, 23.14101841,
       15.03539398, 10.01663565, 14.20062416, 11.9306692 , 12.65214467,
        8.06382676, 16.75303458, 13.14722819, 12.15377001,  9.86233546,
       11.67799829, 16.16740378, 18.79991503, 15.55248867, 11.70081314,
        8.76993604, 10.38142243, 11.6206496 , 12.11852656,  7.5330208 ,
       18.23716181, 12.28110287, 18.28067886, 20.5544014 , 16.26269277,
       21.64306713, 14.61239716, 12.30586853, 11.9012382 ,  8.81

In [ ]:
y_train

166    11.9
26     12.0
44     12.9
64     14.0
182    12.2
       ... 
90     16.7
126    10.6
16     22.4
62     24.2
129    24.7
Name: sales, Length: 160, dtype: float64

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
R2_train = r2_score(y_train, y_pred_train)
R2_test = r2_score(y_test, y_pred_test)
print(R2_train," ",R2_test)

0.8820440065485304   0.8227345476241517


# VIF

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# the independent variables set
X = data[['TV', 'radio', 'newspaper']]

# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns

# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]

print(vif_data)

     feature       VIF
0         TV  2.486772
1      radio  3.285462
2  newspaper  3.055245
